services:
  web:
    build: .
    env_file: .env
    environment:
      - DB_ENGINE=sqlite
      - SQLITE_PATH=/data/db.sqlite3
    volumes:
      - sqlite_data:/data
    ports:
      - "8000:8000"

volumes:
  sqlite_data:
    driver: local
