# Generated by Django 3.2.10 on 2022-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapas',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['player']},
        ),
        migrations.AddField(
            model_name='torneios',
            name='vlr_txadm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
