# Generated by Django 5.2.13 on 2026-04-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapp', '0004_alter_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaBlinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Estrutura de Blinds',
                'verbose_name_plural': 'Estruturas de Blinds',
            },
        ),
        migrations.AddField(
            model_name='torneios',
            name='estrutura_blinds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pkapp.estruturablinds'),
        ),
        migrations.CreateModel(
            name='NivelBlind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('small_blind', models.IntegerField()),
                ('big_blind', models.IntegerField()),
                ('ante', models.IntegerField(default=0)),
                ('duracao_minutos', models.IntegerField(default=20)),
                ('break_apos_minutos', models.IntegerField(default=0)),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='pkapp.estruturablinds')),
            ],
            options={
                'verbose_name': 'Nível de Blind',
                'verbose_name_plural': 'Níveis de Blinds',
                'ordering': ['nivel'],
            },
        ),
    ]
